# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# no trigger on this 'manual' template. The trigger will be a schedule in the scheduled-template.yml
# trigger: none

# no build name as we dynamically set it during the first step based on the isScheduledRun Parameter value
# name: $(Date:yyyyMMdd).$(BuildID)

parameters:
  - name: Repo1_ADF_BuildArtifacts_TagNameOrBuildNumber
    type: string
    default: 'Repo1_ADFPublish5'
    values:
      - 'Repo1_ADFPublish1'
      - 'Repo1_ADFPublish2'
      - 'Repo1_ADFPublish3'
      - 'Repo1_ADFPublish4'
      - 'Repo1_ADFPublish5'
  - name: Repo2_IAC_BuildArtifacts_TagNameOrBuildNumber
    type: string
    default: 'Repo2_IACARMRepo_Publish2'
    values:
      - 'Repo2_IACARMRepo_Publish1'
      - 'Repo2_IACARMRepo_Publish2'
  - name: RunTest1
    type: string
    default: 'true' 
    values:
      - 'true'
      - 'false'
  - name: RunTest2
    type: boolean
    default: true
  - name: RunTest3
    type: boolean
    default: false
  - name: blank_data_warehouse
    type: string
    default: 'no'
    values:
      - 'yes'
      - 'no'
  - name: azureSubDetails
    displayName: 'Connected Azure Subscription Name'
    type: string
    default: 'Azure Subscription (123)' #replace with your service connection
    values:
      - 'Azure Subscription (123)'
  - name: isScheduledRun
    displayName: 'Is isScheduled Run?'
    type: boolean
    default: false

# from: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops
# Two examples of expressions used to define variables
# The first one, a, is evaluated when the YAML file is parsed into a plan.
# The second one, b, is evaluated at run time. 
# Note the syntax ${{}} for parse time and $[] for runtime expressions.
variables:
  - name: vmImage
    value: 'windows-latest'
  - name: a
    value: ${{ true }} # case insensitive, so true, True or TRUE all work. this is evaluated at parse time
  - name: b
    value: $[counter(variables['build.reason'], 0)] # this would evaluate any <expression> at runtime
  - name: version.MajorMinor
    value: '1.2' # Manually adjust the version number as needed for semantic versioning. Revision is auto-incremented.
  - name: version.Revision
    value: $[counter(variables['version.MajorMinor'], 0)] # this will count up each time it is run, up until you change the MajorMinor version number
  - name: versionNumber
    value: '$(version.MajorMinor).$(version.Revision)' # you could use the version number if you wanted, instead of $pBuildName in the first job step below
  - name: vBuildsToday
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 0)] #will restart the counter at 0 each day

stages:
  # this step will download build artifacts from a specific repository & branch, looking for latest for a specific tag. This could be used to pull the build artifacts from across different repositories.
  # - stage: "Download Build Artifacts"
  #   task: DownloadBuildArtifacts@0
  #     inputs:
  #       buildType: 'specific'
  #       project: 'GUID'
  #       pipeline: '1'
  #       specificBuildWithTriggering: true
  #       buildVersionToDownload: 'latestFromBranch' #latest from specific branch with specified tag
  #       branchName: 'refs/heads/master'
  #       tags: '$(Repo2_IAC_BuildArtifacts_TagNameOrBuildNumber)'
  #       downloadType: 'specific'
  #       downloadPath: '$(System.ArtifactsDirectory)'
  - stage: "RunPowershell_toPrintVariablesAndParameters"
    jobs: 
    - deployment: 'test0_0'
      pool:
        vmImage: '$(vmImage)'
      environment: 'none'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: PowerShell@2
                displayName: 'Set the Build Name variable value then assign to the build'
                inputs:
                  targetType: 'inline'
                  script: |
                    Write-Host 'isScheduledRun: "${{ parameters['isScheduledRun'] }}"'
                    if ('${{ parameters['isScheduledRun'] }}' -eq 'False') {
                      [string] $pDateTime = (Get-Date -Format 'yyyyMMddTHHmm')
                      [string] $pBuildID = '$(Build.BuildId)'
                      [string] $pBuildsToday = '$(vBuildsToday)'
                      [string] $pBuildName = "Manual_Build_$($pDateTime)__BuildID_$($pBuildID)__BuildsToday_$($pBuildsToday)__CommitMsg--"
                      Write-Host "'$pDateTime'"
                      Write-Host "'$pBuildID'"
                      Write-Host "'$pBuildsToday'"
                      Write-Host "Setting the name of the build to '$pBuildName'."
                      Write-Host "##vso[build.updatebuildnumber]$pBuildName"
                    } else {
                        Write-Host "Build Name does not need to be changed"
                    }
                  # from here https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#updatebuildnumber-override-the-automatically-generated-build-number
                  # can also this use this code to add a build tag:
                  # ##vso[build.addbuildtag]build tag
              - task: AzureKeyVault@1
                inputs:
                  azureSubscription: '${{ parameters.azureSubDetails }}'
                  KeyVaultName: 'testAKV'
                  SecretsFilter: 'PipelineTestSecret,PipelineTestConnStr'
              - task: AzurePowerShell@5
                inputs:
                  azureSubscription: '${{ parameters.azureSubDetails }}'
                  ScriptType: 'InlineScript'
                  Inline: |
                    echo "Repo1_ADF_BuildArtifacts_TagNameOrBuildNumber: ${{ parameters.Repo1_ADF_BuildArtifacts_TagNameOrBuildNumber }}"
                    echo "Repo2_IAC_BuildArtifacts_TagNameOrBuildNumber: ${{ parameters.Repo2_IAC_BuildArtifacts_TagNameOrBuildNumber }}"
                    echo "RunTest1: ${{ parameters.RunTest1 }}"
                    echo "RunTest2: ${{ parameters.RunTest2 }}"
                    echo "RunTest3: ${{ parameters.RunTest3 }}"
                    echo "vmImage: $(vmImage)"
                    echo "blank_data_warehouse: ${{ parameters.blank_data_warehouse }}"
                    echo "azureSubDetails: ${{ parameters.azureSubDetails }}"
                    echo "PipelineTestSecret: $(PipelineTestSecret)"
                    echo "PipelineTestConnStr: $(PipelineTestConnStr)"
                    echo "a: $(a)"
                    echo "b: $(b)"
                    echo "============================================"
                    if ('${{ parameters.blank_data_warehouse }}' -eq 'no') {
                        echo "This is a no"
                    }
                  errorActionPreference: 'continue'
                  azurePowerShellVersion: 'LatestVersion'

  # - stage: "Run_Test_1"
  #   dependsOn: ""
  # - ${{ if eq(parameters.RunTest1, true) }}:
  - template: stages/child-template.yml
    parameters:
      Stage: 'Run_Test_1'
      DependsOn: 'RunPowershell_toPrintVariablesAndParameters'
      RunTest: '${{ parameters.RunTest1 }}'
      environment: 'dev'
      deploymentNum: '1'
      vmImage: '$(vmImage)'
      blank_data_warehouse: '${{ parameters.blank_data_warehouse }}'
      azureSubName: '${{ parameters.azureSubDetails }}'

  # - stage: "Run_Test_2"
  #   dependsOn: "Run_Test_1"
  # - ${{ if eq(parameters.RunTest2, true) }}:
  - template: stages/child-template.yml
    parameters:
      Stage: 'Run_Test_2'
      DependsOn: 'Run_Test_1'
      RunTest: ${{ parameters.RunTest2 }}
      environment: 'sit'
      deploymentNum: '2'
      vmImage: '$(vmImage)'
      blank_data_warehouse: '${{ parameters.blank_data_warehouse }}'
      azureSubName: '${{ parameters.azureSubDetails }}'

  # - stage: "Run_Test_3"
  #   dependsOn: "Run_Test_2"
  # - ${{ if eq(parameters.RunTest3, true) }}:
  - template: stages/child-template.yml
    parameters:
      Stage: 'Run_Test_3'
      DependsOn: 'Run_Test_2'
      RunTest: ${{ parameters.RunTest3 }}
      environment: 'uat'
      deploymentNum: '3'
      vmImage: '$(vmImage)'
      blank_data_warehouse: '${{ parameters.blank_data_warehouse }}'
      azureSubName: '${{ parameters.azureSubDetails }}'
